package pl.tarasienko.potatosender;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;

public class MainJFrame extends javax.swing.JFrame
{
	private PotatoSender potatoSender;
	
	
	public MainJFrame()
	{
		Toolkit toolkit = Toolkit.getDefaultToolkit();
		setTitle("Potato Sender - wypok.pl");
		setIconImage(toolkit.getImage(getClass().getResource("/res/icon.png")));
		initComponents();

		Dimension screenSize = toolkit.getScreenSize();
		setResizable(false);
		setLocation(new Point(screenSize.width / 2 - getWidth() / 2, screenSize.height / 2 - getHeight() / 2));

		initData();
	}

	private void initData()
	{
		potatoSender = new PotatoSender(jLabel_Status, jButton_Send);
	}

	private void sendPotatoes()
	{
		//<editor-fold desc="Min and Max values validation:">
		int min = 10, max = 10;
		try
		{
			min = Integer.parseInt(jTextField_MinInterval.getText());
			max = Integer.parseInt(jTextField_MaxInterval.getText());

			if(min < 10)
			{
				min = 10;
				jTextField_MinInterval.setText(min + "");
			}
			if(max < 10)
			{
				max = 10;
				jTextField_MaxInterval.setText(max + "");
			}
			if(min > max)
			{
				min = max;
				jTextField_MinInterval.setText(min + "");
			}
		}
		catch(NumberFormatException e)
		{
			min = 30;
			jTextField_MinInterval.setText(min + "");
			max = 120;
			jTextField_MaxInterval.setText(max + "");
		}
		//</editor-fold>

		//<editor-fold desc="Send potatoes:">
		String login = jTextField_Login.getText();
		String password = String.valueOf(jPasswordField_Password.getPassword());
		String message = jTextArea_Message.getText();
		String[] links = jTextArea_Links.getText().split("\\n");

		potatoSender.setData(login, password, min, max, message, links);
		potatoSender.openBrowser();
		//</editor-fold>
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel_Main = new javax.swing.JPanel();
        jButton_Send = new javax.swing.JButton();
        jTextField_Login = new javax.swing.JTextField();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jLabel_Login = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jLabel_Message = new javax.swing.JLabel();
        jLabel_Image = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Message = new javax.swing.JTextArea();
        jLabel_Links = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_Links = new javax.swing.JTextArea();
        jTextField_MinInterval = new javax.swing.JTextField();
        jTextField_MaxInterval = new javax.swing.JTextField();
        jLabel_SendInterval = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_Status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel_Main.setBackground(new java.awt.Color(60, 63, 64));

        jButton_Send.setBackground(new java.awt.Color(60, 63, 64));
        jButton_Send.setFont(new java.awt.Font("DengXian", 1, 12)); // NOI18N
        jButton_Send.setForeground(new java.awt.Color(186, 187, 187));
        jButton_Send.setText("Send");
        jButton_Send.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonSend(evt);
            }
        });
        jButton_Send.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                PropertyChangeOfSendButton(evt);
            }
        });

        jTextField_Login.setBackground(new java.awt.Color(69, 73, 75));
        jTextField_Login.setForeground(new java.awt.Color(186, 187, 187));

        jPasswordField_Password.setBackground(new java.awt.Color(69, 73, 75));
        jPasswordField_Password.setForeground(new java.awt.Color(186, 187, 187));

        jLabel_Login.setFont(new java.awt.Font("DengXian", 1, 12)); // NOI18N
        jLabel_Login.setForeground(new java.awt.Color(186, 187, 187));
        jLabel_Login.setText("Login");

        jLabel_Password.setFont(new java.awt.Font("DengXian", 1, 12)); // NOI18N
        jLabel_Password.setForeground(new java.awt.Color(186, 187, 187));
        jLabel_Password.setText("Password");

        jLabel_Message.setFont(new java.awt.Font("DengXian", 1, 12)); // NOI18N
        jLabel_Message.setForeground(new java.awt.Color(186, 187, 187));
        jLabel_Message.setText("Message");

        jLabel_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/wykopPotato.png"))); // NOI18N

        jScrollPane2.setPreferredSize(new java.awt.Dimension(223, 50));

        jTextArea_Message.setBackground(new java.awt.Color(69, 73, 75));
        jTextArea_Message.setColumns(20);
        jTextArea_Message.setForeground(new java.awt.Color(186, 187, 187));
        jTextArea_Message.setRows(4);
        jTextArea_Message.setText("#charytatywnapyra");
        jScrollPane2.setViewportView(jTextArea_Message);

        jLabel_Links.setFont(new java.awt.Font("DengXian", 1, 12)); // NOI18N
        jLabel_Links.setForeground(new java.awt.Color(186, 187, 187));
        jLabel_Links.setText("Links to images");

        jScrollPane3.setPreferredSize(new java.awt.Dimension(223, 50));

        jTextArea_Links.setBackground(new java.awt.Color(69, 73, 75));
        jTextArea_Links.setColumns(20);
        jTextArea_Links.setForeground(new java.awt.Color(186, 187, 187));
        jTextArea_Links.setRows(5);
        jScrollPane3.setViewportView(jTextArea_Links);

        jTextField_MinInterval.setBackground(new java.awt.Color(69, 73, 75));
        jTextField_MinInterval.setForeground(new java.awt.Color(186, 187, 187));
        jTextField_MinInterval.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_MinInterval.setText("30");
        jTextField_MinInterval.setToolTipText("Sending message in random amount of seconds");

        jTextField_MaxInterval.setBackground(new java.awt.Color(69, 73, 75));
        jTextField_MaxInterval.setForeground(new java.awt.Color(186, 187, 187));
        jTextField_MaxInterval.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_MaxInterval.setText("120");
        jTextField_MaxInterval.setToolTipText("Sending message in random amount of seconds");

        jLabel_SendInterval.setFont(new java.awt.Font("DengXian", 1, 12)); // NOI18N
        jLabel_SendInterval.setForeground(new java.awt.Color(186, 187, 187));
        jLabel_SendInterval.setText("Send interval");
        jLabel_SendInterval.setToolTipText("Sending message in random amount of seconds");

        jLabel8.setForeground(new java.awt.Color(186, 187, 187));
        jLabel8.setText("-");
        jLabel8.setToolTipText("Sending message in random amount of seconds");

        jLabel_Status.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        jLabel_Status.setForeground(new java.awt.Color(186, 187, 187));
        jLabel_Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Status.setText("Offline");

        javax.swing.GroupLayout jPanel_MainLayout = new javax.swing.GroupLayout(jPanel_Main);
        jPanel_Main.setLayout(jPanel_MainLayout);
        jPanel_MainLayout.setHorizontalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_MainLayout.createSequentialGroup()
                        .addComponent(jLabel_Links)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MainLayout.createSequentialGroup()
                        .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_MainLayout.createSequentialGroup()
                                .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Login))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                                .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_SendInterval)
                                    .addGroup(jPanel_MainLayout.createSequentialGroup()
                                        .addComponent(jTextField_MinInterval, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel8)
                                        .addGap(7, 7, 7)
                                        .addComponent(jTextField_MaxInterval, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_MainLayout.createSequentialGroup()
                                .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Message)
                                    .addComponent(jLabel_Password)
                                    .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jButton_Send, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_MainLayout.setVerticalGroup(
            jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MainLayout.createSequentialGroup()
                        .addComponent(jLabel_Login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_MainLayout.createSequentialGroup()
                        .addComponent(jLabel_SendInterval)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_MinInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_MaxInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Links)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel_Status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Send)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSend(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ButtonSend
    {//GEN-HEADEREND:event_ButtonSend
		if(!potatoSender.isWorking())
		{
			sendPotatoes();
		}
		else
		{
			potatoSender.stopSendingPotatoes();
		}
    }//GEN-LAST:event_ButtonSend

    private void PropertyChangeOfSendButton(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_PropertyChangeOfSendButton
    {//GEN-HEADEREND:event_PropertyChangeOfSendButton
		if(jButton_Send.isEnabled() && !jButton_Send.getText().equals("Cancel"))
		{
			jTextField_Login.setEnabled(true);
			jPasswordField_Password.setEnabled(true);
			jTextArea_Message.setEnabled(true);
			jTextArea_Links.setEnabled(true);
			jTextField_MinInterval.setEnabled(true);
			jTextField_MaxInterval.setEnabled(true);
		}
		else
		{
			jTextField_Login.setEnabled(false);
			jPasswordField_Password.setEnabled(false);
			jTextArea_Message.setEnabled(false);
			jTextArea_Links.setEnabled(false);
			jTextField_MinInterval.setEnabled(false);
			jTextField_MaxInterval.setEnabled(false);
		}
    }//GEN-LAST:event_PropertyChangeOfSendButton

	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch(ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch(InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch(IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch(javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		System.setProperty("webdriver.chrome.driver", "E:/Apps/Programowanie/Eclipse/Inne/Biblioteki/Selenium/Drivers/chromedriver.exe");

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new MainJFrame().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Send;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Links;
    private javax.swing.JLabel jLabel_Login;
    private javax.swing.JLabel jLabel_Message;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_SendInterval;
    private javax.swing.JLabel jLabel_Status;
    private javax.swing.JPanel jPanel_Main;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea_Links;
    private javax.swing.JTextArea jTextArea_Message;
    private javax.swing.JTextField jTextField_Login;
    private javax.swing.JTextField jTextField_MaxInterval;
    private javax.swing.JTextField jTextField_MinInterval;
    // End of variables declaration//GEN-END:variables
}
